FROM container4armhf/armhf-golang-bin
MAINTAINER Till Wiese <mail-github.com@till-wiese.de>

RUN set -ex \
  && apk add --no-cache git bash ca-certificates \
  && go get github.com/mholt/caddy/caddy

COPY ["recompile-caddy.bash", "/usr/local/bin/"]
COPY ["etc/caddyplugins.conf", "/etc/"]

ENTRYPOINT ["/usr/local/bin/recompile-caddy.bash"]
